class RINGHTR:
    """
    Ring Heater thermal management component for TRL systems
    """
    
    def __init__(self):
        """
        Initialize Ring Heater with specified parameters
        """
        self.Ppi = 39.0                         # Peak power indicator in mW
        self.resistance_ohm = 34.0              # Heater resistance in Ohms
        self.voltage_v = 3.3                    # Operating voltage in V
        self.target_heat_generated_mw = 78.0    # Target heat generation in mW
        
        # Calculate duty cycle based on target heat generation
        self.duty_cycle = self._calculate_duty_cycle()
        
        # Heat load is the target heat generated (consistent with TRL/DFB style)
        self.ring_htr_heat_load = self.target_heat_generated_mw
    
    def _calculate_duty_cycle(self):
        """
        Calculate duty cycle required to achieve target heat generation
        
        Returns:
            float: Duty cycle (0.0 to 1.0)
        """
        # Maximum power at 100% duty cycle: P_max = V^2 / R
        max_power_mw = (self.voltage_v ** 2 / self.resistance_ohm) * 1000  # Convert to mW
        
        if max_power_mw > 0:
            # Duty cycle = Target Power / Maximum Power
            duty_cycle = self.target_heat_generated_mw / max_power_mw
            return min(max(duty_cycle, 0.0), 1.0)  # Clamp between 0 and 1
        return 0.0
    
    def get_heat_generated(self):
        """
        Get heat generated by the ring heater (identical to TRL/DFB style)
        
        Returns:
            float: Heat generated in mW
        """
        return self.ring_htr_heat_load
    
    def get_power_consumption(self):
        """
        Get power consumption of the ring heater (identical to TRL/DFB style)
        
        Returns:
            float: Power consumption in mW
        """
        return self.ring_htr_heat_load
    
    def get_duty_cycle(self):
        """
        Get the operating duty cycle
        
        Returns:
            float: Duty cycle (0.0 to 1.0)
        """
        return self.duty_cycle
    
    def get_parameters(self):
        """
        Get all ring heater parameters
        
        Returns:
            dict: Dictionary with all parameters
        """
        return {
            'Ppi_mW': self.Ppi,
            'resistance_ohm': self.resistance_ohm,
            'voltage_v': self.voltage_v,
            'target_heat_generated_mw': self.target_heat_generated_mw,
            'duty_cycle': self.duty_cycle,
            'ring_htr_heat_load': self.ring_htr_heat_load
        } 