class RINGHTR:
    """
    Ring Heater class for thermal management in photonic integrated circuits
    """
    
    def __init__(self):
        """
        Initialize Ring Heater with specified parameters
        """
        # Optical parameters
        self.Ppi = 39.0  # Input optical power in mW
        
        # Electrical parameters
        self.resistance_ohm = 34.0  # Nominal resistance in Ohms
        self.voltage_v = 3.3        # Operating voltage in V
        
        # Target heat generation
        self.target_heat_generated_mw = 78.0  # Target heat generation in mW
        
        # Calculate duty cycle to achieve target heat generation
        self.duty_cycle = self._calculate_duty_cycle()
        
        # Heat load parameter
        self.ring_htr_heat_load = self.target_heat_generated_mw
    
    def _calculate_duty_cycle(self):
        """
        Calculate duty cycle required to achieve target heat generation
        
        Returns:
            float: Duty cycle (0 to 1)
        """
        # Maximum power at 100% duty cycle: P_max = V^2 / R
        max_power_mw = (self.voltage_v ** 2 / self.resistance_ohm) * 1000  # Convert to mW
        
        # Duty cycle = Target Power / Max Power
        if max_power_mw > 0:
            duty_cycle = self.target_heat_generated_mw / max_power_mw
            # Clamp duty cycle between 0 and 1
            return min(max(duty_cycle, 0.0), 1.0)
        else:
            return 0.0
    
    def get_heat_generated(self):
        """
        Get the actual heat generated by the ring heater
        
        Returns:
            float: Heat generated in mW
        """
        return self.ring_htr_heat_load
    
    def get_power_consumption(self):
        """
        Get the electrical power consumption
        
        Returns:
            float: Electrical power consumption in mW
        """
        return self.ring_htr_heat_load  # Assuming all electrical power becomes heat
    
    def get_duty_cycle(self):
        """
        Get the calculated duty cycle
        
        Returns:
            float: Duty cycle (0 to 1)
        """
        return self.duty_cycle
    
    def get_parameters(self):
        """
        Get all ring heater parameters
        
        Returns:
            dict: Dictionary containing all parameters
        """
        return {
            'Ppi_mw': self.Ppi,
            'resistance_ohm': self.resistance_ohm,
            'voltage_v': self.voltage_v,
            'duty_cycle': self.duty_cycle,
            'heat_generated_mw': self.ring_htr_heat_load,
            'max_power_mw': (self.voltage_v ** 2 / self.resistance_ohm) * 1000
        } 